### ISSUE TITLE
Teleporting To OW Will Sometimes Put You Into a Wall

### ISSUE THREAD

**Issue by Darkosto** [JackyyTV/DimensionalEdibles#10]
Hello!

When teleporting using the overworld cake, you will sometimes be put into a wall and suffocate. Is there anything that can be done to disallow this?

MC: 1.12.2
Forge: 2796
Dimensional Edibles: 1.2

Thanks!
Darkosto

**Comment by Turkey2349** [comment]
Should be fixed, but I will leave this open for now
