### ISSUE TITLE
Possible to have cakes not use the same coords every time?

### ISSUE THREAD

**Issue by Darkosto** [JackyyTV/DimensionalEdibles#11]
Can you look into allowing cakes placed anywhere to not teleport the player to same exact coords? This wouldn't work too well in multiplayer since players can't spread themselves out.

Thanks!
Darkosto

**Comment by Turkey2349** [comment]
Do you want the coords to be more 1 to 1 mapping or be more like the nether's 200? to 1 mapping between the over world and the nether

**Comment by Darkosto** [comment]
Matching what vanilla does for the 8 to 1 mapping would be fine since that's what most players already know.

**Comment by Turkey2349** [comment]
Fixed in the latest commit
