### ISSUE TITLE
Custom Cake for Twilight Forest Sends Player to 0,0,0 in Dimension 7

### ISSUE THREAD

**Issue by remclave** [JackyyTV/DimensionalEdibles#16]
Is it possible to add an option for the custom cake to ensure the player spawns on the surface of the dimension instead of them spawning in at 0,0,0 and falling into the void beneath the bedrock layer?

**Comment by MokahTGS** [comment]
I know he's planning on adding custom XYZ spawning for custom edibles, but I don't know where he is in that development.
