### ISSUE TITLE
Feature Request: Allow Default Cakes to Never Lose Fuel

### ISSUE THREAD

**Issue by Darkosto** [JackyyTV/DimensionalEdibles#17]
Would you consider making cakes not use fuel when being used? The custom cakes allow this and I would like make the default cakes consistent with that.

Thanks!
Darkasto

**Comment by aultra** [comment]
I added this to my fork.  However, I added some built in cakes for additional dimensions (Erebus, Hunting, Mining, Lost Cities, Twilight Forest, and Simple Void Dimension) to my fork, so I doubt Jackyy will want to pull all my changes into the main branch.
