### ISSUE TITLE
Overworld Apple Teleportation

### ISSUE THREAD

**Issue by Cazadorsniper** [JackyyTV/DimensionalEdibles#19]
Can the overworld apples send the player to their spawn?

**Comment by Turkey2349** [comment]
They teleport you to the last cake/apple used position in the over world

**Comment by Cazadorsniper** [comment]
What if there isn't a cake, the apples were given to them and that was their first time using the apple?

**Comment by Turkey2349** [comment]
If no coords then it takes them to 1/8th of their x and 1/8th of the z and a valid y spawn position

**Comment by Cazadorsniper** [comment]
its just it sends people far away from their base example: https://minecraft.curseforge.com/projects/project-ozone-3-a-new-way-forward/issues/80

**Comment by Turkey2349** [comment]
I see. This would be up to jackky on how he exactly wants to implement a fix

**Comment by Cazadorsniper** [comment]
Ok

**Comment by aultra** [comment]
Dimensional Edibles keeps its own data for where a person teleported from last, and uses that as the return point.  In PO3, is there a different way that people are teleporting to other dimensions before using the dimensional cake or apple?  In my fork, I did make an edit to use a player's bed spawn location if it is available, before using their in world coordinates.  But I'm not sure this will solve the bug that has been reported here, if they have not manually set their own spawn point using a bed.
