### ISSUE TITLE
BUG: Teleportation to height location broken

### ISSUE THREAD

**Issue by Helimyne** [JackyyTV/DimensionalEdibles#2]
DimensionalEdibles-1.12-1.0.jar <--version

Bug: Teleporting to nether put me above top level of bedrock, multiple attempts made, results constant.

Bug: Teleporting to back Overworld to her put me at bottom of overworlds(in stone), multiple attempts made, results constant.

Didn't try the End.

**Comment by JackyyTV** [comment]
Fixed in [1.1](https://minecraft.curseforge.com/projects/dimensional-edibles/files/2641243), sorry this took way longer than it should have as I've been very busy with real life and my new job.
