### ISSUE TITLE
[feature request]  Some way to use apples in creative mode

### ISSUE THREAD

**Issue by Winddbourne** [JackyyTV/DimensionalEdibles#22]
It's slightly annoying that while I'm working on the mod pack I have to leave creative mode to eat the apple and test the dimensional transit every time. It would be nice to have a creative version of each action that activates simply by being clicked on. 

I'm constantly testing transit time, where you land, changes to biome generation, etc . . . and right now every time I change to a dimension that is reached using these foods I have to go into survival, transit to the new dimension, and then go back into creative mode to fly around and check things out.

**Comment by JackyyTV** [comment]
Added in [1.3.2](https://www.curseforge.com/minecraft/mc-mods/dimensional-edibles/files/3195653).
