### ISSUE TITLE
Typo in config file

### ISSUE THREAD

**Issue by DWX12** [JackyyTV/DimensionalEdibles#23]
Just checking out the config file and noticed something odd:
 (TLDR) - Too many cakes and not enough apples in the descriptions

"        # Set to true to enable Custom Cake.
        B:customApple=true

        # Set to true to enable custom Cakes.
        B:customCake=true

        # Set to true to enable End Cake.
        B:endCake=true

        # Set to true to enable Ender Cake.
        B:enderApple=true

        # Set to true to enable Nether Cake.
        B:netherApple=true

        # Set to true to enable Nether Cake.
        B:netherCake=true

        # Set to true to enable Overworld Cake.
        B:overworldApple=true

        # Set to true to enable Overworld Cake.
        B:overworldCake=true"

Great mod. Thank you for all the time, work, and effort that went into this mod.

**Comment by JackyyTV** [comment]
Fixed in [1.3.2](https://www.curseforge.com/minecraft/mc-mods/dimensional-edibles/files/3195653).
