### ISSUE TITLE
Nether cake teleport under the nether.

### ISSUE THREAD

**Issue by Wizardon777** [JackyyTV/DimensionalEdibles#25]
Hello.
I'm maintaining a 1.12.2 modpack called "[Avian Tech](https://www.curseforge.com/minecraft/modpacks/avian-tech)" and got a report from a player that the nether cake drops him in the void under the nether and kills him.
I was able to verify the problem and recreate the bug.

any help would be appreciated.

**Comment by athompson673** [comment]
I would like to add that I was just spawned at the bottom of a lava lake... I feel like the same checks for a vanilla portal should probably also be made (make platform safe / not buried).

**Comment by ManuelGarciaF** [comment]
Also adding that I'm now spawning on the nether roof, I also sometimes spawn hundreds of blocks on the sky.

**Comment by JackyyTV** [comment]
Fixed in [1.3.2](https://www.curseforge.com/minecraft/mc-mods/dimensional-edibles/files/3195653).
