### ISSUE TITLE
Dimension Transport Issues

### ISSUE THREAD

**Issue by Darkosto** [JackyyTV/DimensionalEdibles#3]
Hey Jackyy,

I have an issue with going to other dimensions with your cakes. When teleporting to the Nether and other dimensions, the cake drops you at X:0, Z:0 which is, in most cases, directly over lava. Can you consider adding a platform under the character or checking for blocks underneath them please?

MC: 1.12.2
Mod: 1.12-1.0
Forge: 2760

Thank you!
Darkmosto

**Comment by JackyyTV** [comment]
Hey Darko,

I appreciate you using my mod for SF4 despite the fact that I haven't maintained it for so long. I've been extremely busy with my real life job, so I don't have a lot of time to maintain my mods even if I really want to, but I will try and prioritize an update for this mod ASAP to fix the bugs as I don't want to delay the release for your pack! Thanks for understanding.

\- Jacky

**Comment by JackyyTV** [comment]
Fixed in [1.1](https://minecraft.curseforge.com/projects/dimensional-edibles/files/2641243)!

P.S. Happy birthday Darkosto! 🎉
