### ISSUE TITLE
Feature request: disable end portals activation

### ISSUE THREAD

**Issue by Ganjalf-Amsterdoom** [JackyyTV/DimensionalEdibles#7]
Hi,

could you add a configuration to disable the activation of end portals? or do you know any mod that does that?
I know I can disable strongholds generations but I would like to keep the strongholds, I would like to not activate the portals. (for the infamous end portal dupe bug)

Thank you for your time.

**Comment by JackyyTV** [comment]
What exactly does "activation of end portal" means? I am slightly confused by that.

**Comment by Ganjalf-Amsterdoom** [comment]
Do mentioning of people who are not subbed to the repo works? @asiekierka pardon to boder you, but do you have any suggestion or know any mod out there that disable end portal activation?

**Comment by asiekierka** [comment]
It's probably coremoddable out, but I'm not aware of a particular one.

**Comment by JackyyTV** [comment]
So, after some testing, I've found out that it is actually possible to disable the activation of End Portal via cancelling Forge events, so this will be in the next version of the mod:

[![](https://thumbs.gfycat.com/ImmediateMadeupGrison-size_restricted.gif)](https://gfycat.com/ImmediateMadeupGrison)

Leaving this issue open until I've released the update.
