### ISSUE TITLE
Obsidian platform spawning is too sensitive

### ISSUE THREAD

**Issue by Cazadorsniper** [JackyyTV/DimensionalEdibles#8]
It was reported to me that any time someone eats an Overworld Apple in the nether (maybe some other dimensions too) crashes/kicks people off the server.

* Overworld apple from nether appears to have crashed/kicked people from server (Hypnotizd)

**Comment by Cazadorsniper** [comment]
Since I don't have access to the server files, I'll get Seyeght or OG to get the log for you.

**Comment by JackyyTV** [comment]
Alright. 👍

**Comment by JackyyTV** [comment]
The obsidian spawning seems to be a bit too sensitive too, looks like I'll have to change that.

**Comment by JackyyTV** [comment]
Fixed in [1.2](https://minecraft.curseforge.com/projects/dimensional-edibles/files/2646124).
